version: '3'
services:
  nginx:
    image: nginx
    restart: always
    depends_on:
    - web
    links:
    - web

  web:
    restart: always
    links:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
    - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
    driver: local
  nginx-data:
    driver: local
